[package]
name = "nut-shell"
version = "0.1.0"
authors = ["Max Morehead <20051670+moreheadm@users.noreply.github.com>"]

[dependencies]
liner = "0.4"

[target.'cfg(not(target_os = "redox"))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"
